language: python
dist: xenial
python:
  - 3.6
env:
  CC: gcc
addons:
  apt:
    packages:
      - cmake
      - g++
      - git
      - libboost-date-time-dev
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libboost-regex-dev
      - libboost-signals-dev
      - libboost-system-dev
      - libboost-thread-dev
      - libprotobuf-dev
      - maven
      - protobuf-compiler
      - python
      - python-xmlrunner
      - make
      - unzip
      - wget
      - sbcl
before_install:
  - mkdir upstream
  - cd upstream
  - wget "https://dl.bintray.com/open-rsx/travis-artifacts/rsc-${CC}-master.tar.gz"
  - "tar -xzf rsc-*.tar.gz"
  - wget "https://dl.bintray.com/open-rsx/travis-artifacts/rsb-cpp-${CC}-master.tar.gz"
  - "tar -xzf rsb-cpp-*.tar.gz"
  - wget "https://dl.bintray.com/open-rsx/travis-artifacts/rsb-python-master.tar.gz"
  - "tar -xzf rsb-python-*.tar.gz"
  - wget "https://dl.bintray.com/open-rsx/travis-artifacts/rsb-java-master.tar.gz"
  - "tar -xzf rsb-java-*.tar.gz"
  - cd ..
install:
  - ls upstream

  - pip install wheel pytest
  - pip install upstream/rsb_python-*.whl

  - mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.1:get -DremoteRepositories=file://$(pwd)/upstream/rsb-java -Dartifact=rsb:rsb:1.0-SNAPSHOT

  - wget -O quicklisp.lisp https://beta.quicklisp.org/quicklisp.lisp
  - sbcl --noinform --no-userinit --load quicklisp.lisp --eval '(quicklisp-quickstart:install)' --quit

script:
  - mkdir -p build && cd build
  - ls ../upstream
  - cmake -DCMAKE_PREFIX_PATH="$(pwd)/../upstream/rsc;$(pwd)/../upstream/rsb-cpp" ..
  - make -j3
  - cd ..
  - pytest -v --basetemp=tmp
after_failure:
  - tail -n 100 $(find tmp -type f)
